[workspace]
resolver = "2"

members = [
    "bindings/sirius-bindings",
    "web/backend",
    "web/frontend",
    "web/web_common",
    "web/web_common/web_common_traits",
    "web/web_common/webcodegen",
    "web/web_common/csqlv", 
    "web/web_common/snake-case-sanitizer", 
    "data-retrieval/taxonomy-fetcher",
    "data-retrieval/downloader",
    "web/core_structures",
    "utils/font_awesome",
    "utils/diesel_migrations_utils",
    "utils/common-traits",
    "utils/common-traits-derive",
    "utils/diesel_utils",
]

[workspace.dependencies]
actix-ws = "0.3.0"
syn = {version="2.0", features=["full"]}
quote = "1.0"
proc-macro2 = "1.0"
url = "2.5.4"
indicatif = "0.17.9"
reqwest = {version="0.12.12", features=["stream"]}
futures-util = "0.3.31"
tokio = {version ="1.41.0", features = ["full"]}
flate2 = "1.0.35"
tar = "0.4.43"
infer = "0.16.0"
csv = "1.3.1"
bytes = "1.10.0"
bincode = "1.3.3"
sqlparser = {git = "https://github.com/LucaCappelletti94/sqlparser-rs.git", branch = "gin_trgm_ops"}
diesel = { version = "2.2.5", features = ["serde_json", "postgres", "r2d2", "chrono", "uuid", "extras"] } # uuidv07
diesel-async = {version="0.5.1", features = ["postgres", "pool"]}
postgis_diesel = { git = "https://github.com/LucaCappelletti94/postgis-diesel.git", branch = "master", features = ["serde"], default-features = false }
uuid = { version = "1.11", features = ["serde", "v4", "js"] }
chrono = {version="0.4.38", features = ["serde"]}
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
strum = {version="0.26.3", features=["derive"]}
strum_macros = "0.26.4"
zip = "2.2.2"
taxonomy-fetcher = { path = "data-retrieval/taxonomy-fetcher" }
csqlv = { path = "web/web_common/csqlv" }
font_awesome = {path = "utils/font_awesome"}
testcontainers = {version="0.23.1"}
web_common_traits = { path = "web/web_common/web_common_traits" }
webcodegen = { path = "web/web_common/webcodegen", features = ["postgres_17"] }
diesel_migrations_utils = { path = "utils/diesel_migrations_utils" }
diesel_utils = { path = "utils/diesel_utils" }
common-traits-derive = { path = "utils/common-traits-derive" }
common-traits = { path = "utils/common-traits", features = ["derive"] }
enum_dispatch = "0.3"
core_structures = { path = "web/core_structures" }

[workspace.lints.rust]
missing_docs = "forbid"
unsafe_code = "forbid"
unused_macro_rules = "forbid"
unconditional_recursion = "forbid"
unreachable_patterns = "forbid"
unused_import_braces = "forbid"

[workspace.lints.clippy]
pedantic = "deny"
