[workspace]
resolver = "2"

members = [
    "bindings/sirius-bindings",
    "web/backend",
    "web/frontend",
    "web/web_common",
    "web/web_common/web_common_derive",
    "web/web_common/webcodegen",
    "web/web_common/csqlv",
    "web/web_common/snake-case-sanitizer",
]
