[workspace]
resolver = "2"

members = [
    "bindings/sirius-bindings",
    "web/backend",
    "web/frontend",
    "web/web_common",
    "web/web_common/web_common_traits",
    "web/web_common/webcodegen",
    "web/web_common/csqlv",
    "web/web_common/snake-case-sanitizer",
    "web/web_common/pgrx_validation",
    "web/web_common/pgrx_validation_derive",
    "web/web_common/validation-errors",
    "data-retrieval/taxonomy-fetcher",
    "data-retrieval/downloader",
    "web/core_structures",
    "utils/font_awesome",
    "utils/diesel_migrations_utils",
    "utils/common-traits",
    "utils/common-traits-derive",
    "utils/inflector",
    "utils/time-requirements",
    "data-structures/graph",
    "data-structures/algebra",
    "data-structures/sorted-vec",
]

[workspace.dependencies]
actix-ws = "0.3.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
url = "2.5.4"
indicatif = "0.17.11"
reqwest = { version = "0.12.12", features = ["stream", "json"] }
futures-util = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
flate2 = "1.0.35"
tar = "0.4.43"
infer = "0.16.0"
csv = "1.3.1"
bytes = "1.10.0"
bincode = "1.3.3"
sqlparser = { git = "https://github.com/LucaCappelletti94/sqlparser-rs.git", branch = "gin_trgm_ops" }
diesel = { version = "2.2.7", features = [
    "serde_json",
    "postgres",
    "r2d2",
    "chrono",
    "uuid",
    "extras",
] } # uuidv07
diesel-async = { version = "0.5.2", features = ["postgres", "pool", "bb8"] }
diesel_full_text_search = "2.2"
postgis_diesel = { git = "https://github.com/LucaCappelletti94/postgis-diesel.git", branch = "master", features = [
    "serde",
], default-features = false }
uuid = { version = "1.13", features = ["serde", "v4", "js"] }
chrono = { version = "0.4.39", features = ["serde"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
strum = { version = "0.26.3", features = ["derive"] }
strum_macros = "0.26.4"
zip = "2.2.2"
taxonomy-fetcher = { path = "data-retrieval/taxonomy-fetcher" }
csqlv = { path = "web/web_common/csqlv" }
font_awesome = { path = "utils/font_awesome" }
testcontainers = { version = "0.23.2" }
web_common = { path = "web/web_common" }
web_common_traits = { path = "web/web_common/web_common_traits" }
webcodegen = { path = "web/web_common/webcodegen", features = ["postgres_17"] }
diesel_migrations_utils = { path = "utils/diesel_migrations_utils" }
common-traits-derive = { path = "utils/common-traits-derive" }
common-traits = { path = "utils/common-traits" }
inflector = { path = "utils/inflector" }
core_structures = { path = "web/core_structures" }
regex = "1.11"
plotters = "0.3.7"
futures = "0.3.31"
wasm-bindgen-futures = "0.4.50"
trybuild = "1"
time-requirements = { path = "utils/time-requirements" }
algebra = { path = "data-structures/algebra" }
graph = { path = "data-structures/graph" }
sorted-vec = { path = "data-structures/sorted-vec" }
pgrx_validation = { path = "web/web_common/pgrx_validation" }
pgrx_validation_derive = { path = "web/web_common/pgrx_validation_derive" }
validation-errors = { path = "web/web_common/validation-errors" }

[workspace.lints.rust]
missing_docs = "forbid"
unused_macro_rules = "forbid"
unconditional_recursion = "forbid"
unreachable_patterns = "forbid"
unused_import_braces = "forbid"

[workspace.lints.clippy]
pedantic = "deny"
