[workspace]
resolver = "2"

members = [
    "bindings/sirius-bindings",
    "web/backend",
    "web/frontend",
    "web/web_common",
    "web/web_common/web_common_derive",
    "web/web_common/webcodegen",
    "web/web_common/csqlv", 
    "web/data_migration/directus_migration",
    "web/web_common/snake-case-sanitizer", 
    "data-retrieval/taxonomy-fetcher",
    "data-retrieval/downloader",
]

[workspace.dependencies]
rayon = "1.10.0"
url = "2.5.4"
indicatif = "0.17.9"
reqwest = {version="0.12.12", features=["stream"]}
futures-util = "0.3.31"
tokio = {version ="1.41.0", features = ["full"]}
flate2 = "1.0.35"
tar = "0.4.43"