[package]
name = "backend"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/earth-metabolome-initiative/emi-monorepo"
license = "GPL-3.0"
keywords = ["metabolomics", "database", "backend", "web", "api"]
readme = "README.md"
categories = ["science", "database", "web", "api"]
authors = ["Earth Metabolome Initiative"]
description = "Backend for the Earth Metabolome Initiative"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono.workspace = true
diesel.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
postgis_diesel.workspace = true

sqlx = { version = "0.7.3", features = ["runtime-async-std-native-tls", "postgres", "chrono", "uuid"] }
openssl = { version = "0.10" }

actix = "0.13.3"
actix-cors = "0.7.0"
actix-rt = "2.9.0"
actix-web = {version="4.5", features=["cookies", "openssl"]}
actix-web-httpauth = "0.8.1"
actix-service = "2.0.2"
actix-http = "3.6.0"
actix-web-actors = "4.3.0"
actix-files = "0.6.5"
log = "0.4"
env_logger = "0.9"
futures = "0.3.8"
r2d2 = "0.8"
rust-argon2 = "1.0"
time = "0.3"
jsonwebtoken = "9.2.0"
reqwest = {version="0.12.4", features = ["blocking", "json"] }
email_address = "0.2.4"
web_common = { path = "../web_common", features = ["backend"] }
redis = { version = "0.24.0", features = ["tokio-comp"] }
base64 = "0.21.7"
validator = "0.16"
bincode = "1.3.3"
image = "0.25.0"
identicon-rs = "5.0.1"
strsim = "0.11.1"
