[package]
name = "backend"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/earth-metabolome-initiative/emi-monorepo"
license = "GPL-3.0"
keywords = ["metabolomics", "database", "backend", "web", "api"]
readme = "README.md"
categories = ["science", "database", "web", "api"]
authors = ["Earth Metabolome Initiative"]
description = "Backend for the Earth Metabolome Initiative"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
dotenvy = "0.15.7"
diesel = { version = "2.1.4", features = ["postgres", "r2d2", "chrono", "uuid", "extras"] } # uuidv07
serde = { version = "1.0.195", features = ["derive"] }
sqlx = { version = "0.7.3", features = ["runtime-async-std-native-tls", "postgres", "chrono", "uuid"] }
serde_json = "1.0"
openssl = { version = "0.10" }

bigdecimal = "0.4.2"
actix-rt = "2.9.0"
actix-web = {version="4.5", features=["cookies", "openssl"]}
actix-web-httpauth = "0.8.1"
actix-service = "2.0.2"
actix-web-actors = "4.3.0"
derive_more = "0.99"
log = "0.4"
env_logger = "0.9"
futures = "0.3.8"
lazy_static = "1.4"
r2d2 = "0.8"
rust-argon2 = "1.0"
uuid = { version = "1.7", features = ["serde", "v4", "js"] }
time = "0.3"
actix-cors = "0.7.0"
jsonwebtoken = "9.2.0"
reqwest = {version="0.11.24", features = ["blocking", "json"] }
email_address = "0.2.4"
web_common = { path = "../web_common", features = ["backend"] }
redis = { version = "0.24.0", features = ["tokio-comp"] }
base64 = "0.21.7"
actix-files = "0.6.5"
validator = "0.16"
actix = "0.13.3"
bincode = "1.3.3"

[profile.release]
# Less code to include into binary
panic = 'abort'
# Optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# Optimization for size ( most aggressive )
opt-level = 'z'
# Link time optimization using using whole-program analysis
lto = true
