[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.31", features = ["serde"] }
dotenvy = "0.15.7"
diesel = { version = "2.1.4", features = ["postgres", "r2d2", "chrono", "uuid"] }
serde = { version = "1.0.195", features = ["derive"] }
thiserror = "1.0.56"