[package]
name = "web_common"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/earth-metabolome-initiative/emi-monorepo"
license = "GPL-3.0"
keywords = ["science", "database", "web", "api"]
readme = "README.md"
categories = ["science", "database", "web", "api"]
authors = ["Earth Metabolome Initiative"]
description = "Utilities for the Earth Metabolome Initiative"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.7", features = ["serde", "v4", "js"] }
validator = { version = "0.16", features = ["derive"] }
log = "0.4"

# We need to be able to implement the From trait for types defined in third
# party crates that are used in the backend and frontend. In order to do so,
# we define two features that are used to enable the implementation of the
# From trait for types defined in third party crates respectively in the
# backend and frontend. The features are called `backend` and `frontend`.

actix-web-actors = { version = "4.3.0", optional = true }
actix-web = { version = "4.0", optional = true }

gloo-net = {version="0.5.0", features=["websocket"], optional = true}
bincode = "1.3.3"
bytes = {version="1.5.0", optional = true}
actix = {version="0.13.3", optional = true}

web_common_derive = { path = "web_common_derive" }
rustrict = "0.7.24"
image = "0.23.0"
js-sys = "0.3.69"
rustface = { version="0.1.7", optional = true }
nude = {version="0.3.0", optional = true }
wasm-bindgen-futures = {version="0.4.42", optional = true}
futures-util = "0.3.30"
wasm-bindgen = {version="0.2.92", optional = true}

[dependencies.web-sys]
version = "0.3.69"
optional = true
features = [
    "FileReaderSync"
]

[features]
# The `backend` feature is used to enable the implementation of the From trait
# for types defined in third party crates in the backend.
backend = [ "actix-web", "actix-web-actors", "bytes", "actix", "rustface", "nude" ]

# The `frontend` feature is used to enable the implementation of the From trait
# for types defined in third party crates in the frontend.
frontend = ["gloo-net", "web-sys", "wasm-bindgen-futures", "wasm-bindgen"]
