[package]
name = "webcodegen"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.4", features = ["postgres", "chrono", "uuid", "64-column-tables"] }
itertools = "0.13.0"
pluralizer = "0.4.0"
regex = "1.11.1"
serde = { version = "1.0.214", features = ["derive"] }
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
prettyplease = "0.2"
sqlparser = "0.52.0"
snake-case-sanitizer = {path = "../snake-case-sanitizer"}

[dev-dependencies]
diesel_migrations = "2.2.0"
testcontainers = {version="0.23.1"}
tokio = {version ="1.41.0", features = ["full"]}
trybuild = "1.0.101"
serde_json = "1.0.132"
chrono = {version="0.4.38", features = ["serde"]}
ipnetwork = "0.20.0"
diesel_full_text_search = "2.2.0"
diesel-async = {version="0.5.1", features = ["postgres", "pool"]}
uuid = {version="1.11.0", features = ["serde", "v4"]}
macaddr = "1.0.1"
postgis_diesel = "2.4.1"

[features]
default = ["diesel", "serde"]
serde = []
diesel = []
postgres_17 = ["diesel"]
