[package]
name = "webcodegen"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.4", features = ["postgres", "64-column-tables"] }
itertools = "0.13.0"
serde = { version = "1.0.214", features = ["derive"] }
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
prettyplease = "0.2"

[dev-dependencies]
diesel_migrations = "2.2.0"
testcontainers = {version="0.23.1"}
tokio = {version ="1.41.0", features = ["full"]}
