[package]
name = "webcodegen"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.4", features = ["postgres", "chrono", "uuid", "64-column-tables"] }
itertools = "0.13.0"
pluralizer = "0.4.0"
regex = "1.11.1"
serde.workspace = true
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
prettyplease = "0.2"
snake-case-sanitizer = {path = "../snake-case-sanitizer"}
sqlparser.workspace = true

[dev-dependencies]
diesel_migrations = "2.2.0"
testcontainers = {version="0.23.1"}
tokio.workspace = true
trybuild = "1.0.101"
serde_json = "1.0.132"
chrono.workspace = true
ipnetwork = "0.20.0"
diesel_full_text_search = "2.2.0"
diesel-async = {version="0.5.1", features = ["postgres", "pool"]}
uuid.workspace = true
web_common_traits = {workspace = true, features = ["backend"]}
macaddr = "1.0.1"
postgis_diesel.workspace = true

[features]
default = ["diesel", "serde"]
serde = []
diesel = []
postgres_17 = ["diesel"]
