[package]
name = "csqlv"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
diesel = "2.2.5"
flate2 = "1.0.35"
indicatif = "0.17.9"
quote = "1.0.37"
uuid.workspace = true
inflector.workspace = true

[dev-dependencies]
testcontainers = {version="0.23.1"}
tokio = {version ="1.41.0", features = ["full"]}
trybuild = "1.0.101"
serde_json = "1.0.132"
chrono.workspace = true
ipnetwork = "0.20.0"
diesel-async.workspace = true
macaddr = "1.0.1"
postgis_diesel.workspace = true

[features]
default = [ "serde"]
serde = []
diesel = []
