[package]
name = "csqlv"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
diesel.workspace = true
flate2 = "1.0.35"
indicatif = "0.17.11"
quote = "1.0.38"
uuid.workspace = true
inflector.workspace = true
const_format = "0.2.34"

[dev-dependencies]
testcontainers = {version="0.23.2"}
tokio = {version ="1.43.0", features = ["full"]}
trybuild.workspace = true
serde_json = "1.0.138"
chrono.workspace = true
ipnetwork = "0.20.0"
macaddr = "1.0.1"
postgis_diesel.workspace = true
diesel = {workspace = true, features = ["postgres"]}

[features]
default = [ "serde"]
serde = []
