[package]
name = "web_common_traits"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid.workspace = true
serde.workspace = true
diesel = {workspace = true, optional = true}
diesel-async =  { workspace = true, optional = true }
common-traits.workspace = true
enum_dispatch.workspace = true

[features]
frontend = []
backend = ["dep:diesel-async", "dep:diesel"]

[lints]
workspace = true