[package]
name = "web_common_traits"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid.workspace = true
serde = { workspace = true, optional = true }
diesel = {workspace = true, optional = true}
diesel-async =  { workspace = true, optional = true }
common-traits.workspace = true

[features]
frontend = []
backend = ["dep:diesel-async", "dep:diesel"]
serde = ["dep:serde", "common-traits/serde"]

[lints]
workspace = true