[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/earth-metabolome-initiative/emi-monorepo"
license = "GPL-3.0"
keywords = ["metabolomics", "database", "frontend", "web", "api"]
readme = "README.md"
categories = ["science", "database", "web", "api"]
authors = ["Earth Metabolome Initiative"]
description = "Frontend for the Earth Metabolome Initiative"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo = "0.11.0"
reqwasm = "0.5.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
wasm-bindgen = "0.2.90"
uuid = { version = "1.7", features = ["serde", "v4", "js"] }
wasm-bindgen-futures = "0.4.40"
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
yewdux = "0.10.0"
web_common = { path = "../web_common" }
gloo-net = "0.5.0"
gloo-console = "0.3.0"
gluesql = { version = "0.15", features = ["idb-storage"], default-features = false }
wasm-logger = "0.2.0"
log = "0.4.20"
validator = { version = "0.16", features = ["derive"] }

[dependencies.web-sys]
version = "0.3.67"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
  'HtmlDocument',
  'HtmlInputElement',
  'HtmlFormElement',
  'Navigator',
  'FormData'
]


[profile.release]
# Less code to include into binary
panic = 'abort'
# Optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# Optimization for size ( most aggressive )
opt-level = 'z'
# Link time optimization using using whole-program analysis
lto = true