[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/earth-metabolome-initiative/emi-monorepo"
license = "GPL-3.0"
keywords = ["metabolomics", "database", "frontend", "web", "api"]
readme = "README.md"
categories = ["science", "database", "web", "api"]
authors = ["Earth Metabolome Initiative"]
description = "Frontend for the Earth Metabolome Initiative"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo = "0.11.0"
reqwasm = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasm-bindgen = "0.2.92"
uuid.workspace = true
wasm-bindgen-futures = "0.4.40"
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
# The doc-tests feature is required to avoid errors from the Rust Analyzer,
# but it is not actually used in the code.
yewdux = { version = "0.10.0", features = ["doctests"] }
web_common = { path = "../web_common", features = ["frontend"] }
gloo-net = "0.5.0"
gloo-console = "0.3.0"
wasm-logger = "0.2.0"
log = "0.4.20"
validator = { version = "0.16", features = ["derive"] }
futures = "0.3.30"
bincode = "1.3.3"
rustrict = "0.7.24"
js-sys = "0.3.69"
leaflet = "0.4.0"
chrono.workspace = true
sublime_fuzzy = "0.7.0"
implicit-clone = "0.4.9"
v = "0.1.0"
image = "0.24.0"
base64 = "0.22.1"
rxing = { version = "0.5.9", features = [
  "wasm_support",
], default-features = false }
yew-hooks = "0.3.2"
postcard = "1.0.8"
serde-wasm-bindgen = "0.6.5"
yew-agent = "0.3.0"
rustfft = "6.2.0"
regex = "1.10.5"
strsim = "0.11.1"
core_structures = { workspace = true, features = ["frontend"]}

[dependencies.web-sys]
version = "0.3.69"
features = [
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
  'Document',
  'HtmlDocument',
  'HtmlInputElement',
  'HtmlFormElement',
  'Navigator',
  'FormData',
  'File',
  'HtmlDivElement',
  'MediaDeviceKind',
  'MediaRecorder',
  'DataTransfer',
  'Blob',
  'Url',
  'FileReader',
  'EventTarget',
  'Geolocation',
  'Coordinates',
  'Position',
  'PositionOptions',
  'ImageCapture',
  'MediaCapabilities',
  'PositionError',
  'HtmlAnchorElement',
  "CanvasRenderingContext2d",
  "MediaDevices",
  "MediaDeviceInfo",
  "MediaStream",
  "HtmlCanvasElement",
  "HtmlVideoElement",
  "MediaStreamConstraints",
  "MediaTrackConstraints",
  "VideoFacingModeEnum",
  "MediaStreamTrack",
  "Navigator",
  "ImageData",
]
