name: Sirius


on:
  push:
    paths:
      - "bindings/sirius/**"
    branches: ["main"]
  pull_request:
    paths:
      - "bindings/sirius/**"
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  sirius:
    runs-on: ubuntu-latest
    environment: Sirius
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve Sirius install script
        run: |
          wget https://raw.githubusercontent.com/enpkg/enpkg_full/emikg-adapt/src/install_sirius.sh
          chmod +x install_sirius.sh
      - name: Install Sirius
        run: |
          bash ./install_sirius.sh
          sudo chmod -R 755 $GITHUB_WORKSPACE/sirius
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run tests
        run: | 
          export SIRIUS_PATH=${{vars.SIRIUS_PATH}}
          export SIRIUS_USERNAME=${{vars.SIRIUS_USERNAME}}
          export SIRIUS_PASSWORD=${{vars.SIRIUS_PASSWORD}}
          cargo test --test test_sirius

